services:
  server:
    build: .
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - test_network
    volumes:
      - .:/app
      - ~/.vscode-server:/root/.vscode-server
    command: sh -c "make clean && make && tail -f /dev/null"

  client:
    build: .
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - test_network
    volumes:
      - .:/app
      - ~/.vscode-server:/root/.vscode-server
    command: sh -c "make clean && make && tail -f /dev/null"  

networks:
  test_network:
    driver: bridge
