services:
  server:
    build: .
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - test_network
    volumes:
      - .:/app
      - ~/.vscode-server:/root/.vscode-server
    command: sh -c "make clean && make && tail -f /dev/null" # Build only happens in one container. Other containers will share via volume mount.

  client:
    build: .
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - test_network
    volumes:
      - .:/app
      - ~/.vscode-server:/root/.vscode-server

networks:
  test_network:
    driver: bridge
